apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret

type: Opaque

data:
  MONGO_URI:  {{ .Values.secret.MONGO_URI | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
